-- Copy and paste this directly into your Supabase SQL Editor
-- This will create the required tables for your ESP32 Hardware

-- 1. Create the Sensor Data Table (Stores all historical sensor readings)
CREATE TABLE sensor_data (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  temperature numeric,
  humidity numeric,
  moisture integer,
  co2 integer,
  light integer
);

-- Note: In a production app, you would set up Row Level Security (RLS). 
-- For hardware testing, disabling RLS makes it easier for the ESP32 to write data without an auth token:
ALTER TABLE sensor_data DISABLE ROW LEVEL SECURITY;

-- 2. Create the Actuators Table (Stores switch states for the dashboard)
CREATE TABLE actuators (
  id bigint generated by default as identity primary key,
  mist_maker boolean default false,
  cooling_fan boolean default false,
  relay3 boolean default false,
  relay4 boolean default false,
  grow_light_pwm integer default 0
);

-- Disable RLS for easy reading/writing from ESP32
ALTER TABLE actuators DISABLE ROW LEVEL SECURITY;

-- 3. Insert the default row!
-- The ESP32 is looking for row ID=1, so we MUST insert it.
INSERT INTO actuators (id, mist_maker, cooling_fan, relay3, relay4, grow_light_pwm)
VALUES (1, false, false, false, false, 0);
